### ISSUE TITLE
Question: Which functions check for equality?

### ISSUE THREAD

**Issue by PLukas2018** [shrBadihi/EqBench#2]
Is there a simple way to find out which functions for each project should an equivalence checking tool check for equality? (Specifically talking about the C versions of the programs.)

So far I found out that:
- for the `CLEVER` benchmark the function that should be checked is probably included in the field `program name` (after a dot) in `Desc.json` file of each program,
- for programs that do not contain `*.json` file I think mostly all functions located in the file can be evaluated, but there are exceptions e.g. `constructor` function in `Neq` version of the program `hashCode` in `ej_hash` benchmark, ...
- for programs that do contain `*.json` file should probably be checked the function that is:
  - often called `snippet` (e.g. in `benchmarks/caldat/badluk/Neq`) or
  - has the same name as the name of the program (e.g. `benchmarks/airy/beschb/Neq`) or
  - the name of the function 'contains' the name of the program (e.g. `benchmarks/raytrace/sphere/Neq`)
  - ...

I guess that the `Eq` versions of programs are not a big deal because there should be all functions in the file evaluated as equal,
but the problem is in `Neq` versions because it often contains some equal functions and usually one not equal.

**Comment by shrBadihi** [comment]
- For REVE, there is only one method (called _f_) in each project. 
- For CLEVER, there are two methods in each project. If you are performing program-level equivalence, where the entry method might not be changed but it calls a changed method, then yes, the method is the one after the dot in Desc.json. Otherwise (i.e., in the case of method-level analysis), use the other method that is actually changed between the two versions. 
- For the remaining projects, there are folders for each main project where only one method is changed, e.g., benchmarks/airy/beschb where only method _beschb_ is changed in the _airy_ project. As you said, that particular method is called either the name of the folder or "snippet", or contains the name. I believe if you look for these patterns in each project, then you will find the method to compare. Another solution would be to compare the _old_ and _new_ versions for each folder and then each method pair with a different code can be checked for equivalence.  The folders without .json files (e.g., benchmarks/ej_hash/ej_hash that you pointed out) are the programs where all methods have been changed. They have the name of the project (e.g., benchmarks/airy/airy) or name+"Program" (e.g., benchmarks/caldat/caldatProgram). Basically, it is an aggregated form of all other subfolders for a project so it does not have a .json file. If you are not doing program-level equivalence checking, then you don't need to perform your analysis using these projects. 

Hope that helps! 

When I find time, I will add the "method name" to the descriptions for both C and Java versions.

**Comment by PLukas2018** [comment]
Yes, I think it helped a bit. Thank you very much for a clarification.

**Comment by shrBadihi** [comment]
I've added the "function name" to C-Desc.json files for each EQ and NEQ version of all projects. Similarly, for Java versions, I've also added "method name" to J-Desc.json files. Please see the latest commit.

**Comment by PLukas2018** [comment]
Thank you very much for the quick update.

**Comment by PLukas2018** [comment]
> * For CLEVER, there are two methods in each project. If you are performing program-level equivalence, where the entry method might not be changed but it calls a changed method, then yes, the method is the one after the dot in Desc.json. **Otherwise (i.e., in the case of method-level analysis), use the other method that is actually changed between the two versions.**

I found out that at least in some programs of CLEVER benchmarks, it is probably not possible to compare the changed function/method (do method-level analysis), but it is necessary to do program-level analysis (compare the function which is after a dot in `program name` field in the *.json file).

Example `benchmarks/CLEVER/multiple/Eq`:

```c
// old version:
int lib(int x) {
	return x % 5;
}
int client(int x){
	x = x*5*6;
	if (lib(x)==0){
		return 1;
	}else{
		return 0;
	}
}
```

```c
// new version:
int lib(int x) {
	return x % 6;
}
int client(int x){
	x = x*5*6;
	if (lib(x)==0){
		return 1;
	}else{
		return 0;
	}
}
```
`lib` contains change but is not equal on its own, but `client` is equal even tho that the `lib` function changed 

Similarly for eg. `benchmarks/CLEVER/UnchLoop/Neq`, where `foo` contains change but is equal (if I am not mistaken) but the `main` function is not equal. 

I will do a program-level analysis for the CLEVER benchmark, just wanted to update this comment/issue.

**Comment by shrBadihi** [comment]
Yes, that is correct. CLEVER was originally created for a program-level analysis. As such, the labels of Eq/Neq are based on the program-level analysis. It is highly possible that if one wants to do method-level analysis for these benchmarks the labels might be different for the changed methods.

**Comment by PLukas2018** [comment]
@shrBadihi I would like to check with you on a few things:

> * For REVE, there is **only one method** (called _f_) in each project.

For `REVE/triangular/Eq`, `REVE/triangularMod/Eq`, `REVE/triangularMod/Neq` there are two functions in the programs and it looks like similarly to the `CLEVER` benchmarks that for these programs functions which are mentioned in the `C-Desc.json` file in the `program name` field after a dot should be analysed:
- for `REVE/triangular/Eq` `triangle` function,
- for `REVE/triangularMod/Eq` `f` function and
- for `REVE/triangularMod/Neq` `f` function.

> * The folders without .json files (e.g., benchmarks/ej_hash/ej_hash that you pointed out) are the programs where **all methods have been changed**. They have the name of the project (e.g., benchmarks/airy/airy) or name+"Program" (e.g., benchmarks/caldat/caldatProgram). Basically, it is an aggregated form of all other subfolders for a project so it does not have a .json file.

It looks like in some 'aggregated' C programs, not all functions have been changed, and at least for the Neq variants, these should not be analysed. The functions are:
- for  `ej_hash/ej_hash/Neq`: `constructor`,
- for `ej_hash/ej_hash/Eq`:  `constructor`,
- for `raytrace/raytrace/Neq`: `Vector3DConstructor`, `Vector3DConstructor2`, `SurfaceConstructor`,
- for `raytrace/raytrace/Eq`: `Vector3DConstructor`, `Vector3DConstructor2`, `SurfaceConstructor`,
- for `tcas/tcas/Neq`: `Own_Below_Threat`, `Own_Above_Threat`, `Inhibit_Biased_Climb`, `ALIM`,
- for `tcas/tcas/Eq`: `Own_Below_Threat`, `Own_Above_Threat`, `Inhibit_Biased_Climb`, `ALIM`,
- for `ell/ellProgram/Neq`: `SQR`, `SIGN`, `MAX`, `MIN`,
- for `ell/ellProgram/Eq`: `SQR`, `SIGN`, `MAX`, `MIN`,
- for `gam/gam/Neq`: `gammln`,
- for `gam/gam/Eq`: `gammln`,
- for `frenel/frenelProgram/Neq`: `getreal`, `getimag`, `constructor`, `constructor2`, `assign`, `assignObj`, `plus`, `minus`, `multiply`, `divide`,
- for `frenel/frenelProgram/Eq`: `getreal`, `getimag`, `constructor`, `constructor2`, `assign`, `assignObj`, `plus`, `minus`, `multiply`, `divide`.

Is that correct, and are there any other functions that should not be analysed? Alternatively, did I misunderstand how these benchmarks should be used with the equivalence checking tool? I understood it as analyzing each function in the 'aggregated' program and evaluating all functions as equal/not-equal based on the directory they are in (skipping the mentioned functions to ensure correct evaluation). Was this the intended approach, or was it meant otherwise?

---
Btw. I apologize for the references spam on this issue. I did not realize GitHub would do this, it was not intentional.
